export default {
  ADD_ITEM: 'ADD_ITEM',
  CHANGE_QUANTITY: 'CHANGE_QUANTITY',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CHECK_DELIVERY_ZONE: 'CHECK_DELIVERY_ZONE',
  FETCH_RESTAURANT: 'FETCH_RESTAURANT',
  CHANGE_ACTIVE_COURSE: 'CHANGE_ACTIVE_COURSE',
}
