export default {
  ADD_ITEM: 'ADD_ITEM',
  CACHE_COURSES: 'CACHE_COURSES',
  CACHE_MENU_ITEMS: 'CACHE_MENU_ITEMS',
  CACHE_TYPES: 'CACHE_TYPES',
  CHANGE_QUANTITY: 'CHANGE_QUANTITY',
  CLEAR_CART: 'CLEAR_CART',
  COMPLETE_NEW_USER: 'COMPLETE_NEW_USER',
  FETCH_RESTAURANT: 'FETCH_RESTAURANT',
  HIDE_DIALOG: 'HIDE_DIALOG',
  HIDE_SNACKBAR: 'HIDE_SNACKBAR',
  NEW_ADDRESS: 'NEW_ADDRESS',
  REMOVE_ITEM: 'REMOVE_ITEM',
  SHOW_DIALOG: 'SHOW_DIALOG',
  SHOW_SNACKBAR: 'SHOW_SNACKBAR',
  UPDATE_ITEM: 'UPDATE_ITEM'
}
