export default {
  ADD_ITEM: 'ADD_ITEM',
  CACHE_COURSES: 'CACHE_COURSES',
  CACHE_MENU_ITEMS: 'CACHE_MENU_ITEMS',
  CHANGE_ACTIVE_COURSE: 'CHANGE_ACTIVE_COURSE',
  CHANGE_QUANTITY: 'CHANGE_QUANTITY',
  CHECK_DELIVERY_ZONE: 'CHECK_DELIVERY_ZONE',
  FETCH_RESTAURANT: 'FETCH_RESTAURANT',
  REMOVE_ITEM: 'REMOVE_ITEM',
  UPDATED_SELECTED_COURSE: 'UPDATED_SELECTED_COURSE',
}
